/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as SellRouteImport } from './routes/sell'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as PropertySlugRouteImport } from './routes/property.$slug'
import { Route as AdminPropertyIdRouteImport } from './routes/admin.property.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertyIdRoute = AdminPropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/properties': typeof PropertiesRoute
  '/sell': typeof SellRoute
  '/admin/new': typeof AdminNewRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/property/$id': typeof AdminPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/properties': typeof PropertiesRoute
  '/sell': typeof SellRoute
  '/admin/new': typeof AdminNewRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/property/$id': typeof AdminPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/properties': typeof PropertiesRoute
  '/sell': typeof SellRoute
  '/admin/new': typeof AdminNewRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/property/$id': typeof AdminPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/calculator'
    | '/compare'
    | '/journal'
    | '/login'
    | '/partner'
    | '/properties'
    | '/sell'
    | '/admin/new'
    | '/journal/$slug'
    | '/property/$slug'
    | '/admin/'
    | '/admin/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/calculator'
    | '/compare'
    | '/journal'
    | '/login'
    | '/partner'
    | '/properties'
    | '/sell'
    | '/admin/new'
    | '/journal/$slug'
    | '/property/$slug'
    | '/admin'
    | '/admin/property/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/calculator'
    | '/compare'
    | '/journal'
    | '/login'
    | '/partner'
    | '/properties'
    | '/sell'
    | '/admin/new'
    | '/journal/$slug'
    | '/property/$slug'
    | '/admin/'
    | '/admin/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  CompareRoute: typeof CompareRoute
  JournalRoute: typeof JournalRouteWithChildren
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  PropertiesRoute: typeof PropertiesRoute
  SellRoute: typeof SellRoute
  PropertySlugRoute: typeof PropertySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/property/$id': {
      id: '/admin/property/$id'
      path: '/property/$id'
      fullPath: '/admin/property/$id'
      preLoaderRoute: typeof AdminPropertyIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPropertyIdRoute: typeof AdminPropertyIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPropertyIdRoute: AdminPropertyIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  CompareRoute: CompareRoute,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  PropertiesRoute: PropertiesRoute,
  SellRoute: SellRoute,
  PropertySlugRoute: PropertySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
